fix: non-remote bulk-download working
Zendro-dev/zendro pull request #32
Opened 2023-08-21 12:15 UTC by qwerdenkerXD

2023-08-21 12:23 UTC, qwerdenkerXD commented
Line 36 should be generalized, is sql-only now

2023-10-13 13:18 UTC, wunderbarr requested changes

2023-10-13 13:18 UTC, wunderbarr commented on lib/bulk_download.js
> +      ? path.resolve(options.file_path)
have a look at Windows, whether `resolve` function works

2023-10-13 13:18 UTC, wunderbarr commented on lib/bulk_download.js
>        : path.normalize(
keep the consistency with resolve function

2023-10-17 04:11 UTC, qwerdenkerXD commented on lib/bulk_download.js
> +      ? path.resolve(options.file_path)
works

2023-10-17 08:51 UTC, merged